name: Example add-on
version: "1.2.8"
slug: example
description: Example add-on
init: true
host_network: true
full_access: true
url: "https://github.com/PatrickEwald/ha_addons/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
options:
  message: "Hello world..."
  username: "patrick"
  password: "test"
schema:
  message: "str?"
  username: "str"
  password: "str"
privileged:
  - SYS_ADMIN
  - NET_ADMIN
build_from:
  amd64: "ghcr.io/hassio-addons/base:14.1.1"
  aarch64: "ghcr.io/hassio-addons/base:14.1.1"
  armv7: "ghcr.io/hassio-addons/base:14.1.1"
  armhf: "ghcr.io/hassio-addons/base:14.1.1"
  i386: "ghcr.io/hassio-addons/base:14.1.1"
