#!/usr/bin/with-contenv sh
set -ex

echo "== RUN start =="
date
echo "PWD: $(pwd)"
echo "Listing /app:"
ls -la /app || true
echo "Python version:"
python3 -V || true

while true; do
  echo "Invoking python..."
  python3 -u /app/amazon.py 2>&1 | tee -a /data/amazon.log || echo "python exit code: $?"
  echo "Sleeping 30s..."
  sleep 30
done
