name: Forecast Builder
version: "1.0.2"
slug: forecast_builder
description: Alle 5 Minuten aktuelle Daten abholen, Auslastung prognostizieren und in InfluxDB speichern
url: "https://github.com/PatrickEwald/ha_addons/tree/main/forecast-builder"
init: false
startup: application
boot: auto
host_network: true
arch:
  - amd64
  - aarch64
  - armv7

options:
  use_temperature: false
  use_bridge_day: false
  use_lags: false
  influx_user: ""
  influx_password: ""
  interval: 300 # Sekunden; Standard = 15 min
schema:
  use_temperature: "bool"
  use_bridge_day: "bool"
  use_lags: "bool"
  influx_user: "str"
  influx_password: "str"
  interval: int
